---
# Defines services, you can mix and match services to the same IPs
# Just define where the services live and follow the guidance in the
# inventory for a smooth deployment.

cloudstack_mgmt: # Single hosts
  hosts: 
    192.168.1.3:
kvm_host: # Can be multiple
  hosts:
    192.168.1.4:
nfs_server: # Can be multiple
  hosts:
    192.168.1.5:
ceph:
  children:
    ceph_mon: # Odd number of host reccommended
      hosts:
        192.168.1.5:
        192.168.1.6:
        192.168.1.7:
    ceph_mgr: # Single host
      hosts:
        192.168.1.5:
    ceph_osd: # Should be multiple hosts, ideally at least three
      hosts:
        192.168.1.5:
        192.168.1.6:
        192.168.1.7:
        192.168.1.8:
