---
# Ceph vars

ceph_dashboard_user: "{{ ansible_user }}"

ceph_dashboard_password: "{{ vault_ceph_dashboard_password }}"

# KVM vars

cloudstack_agent_ssh_user: "{{ ansible_user }}" # The user Cloudstack will use to manage the cluster.

cloudstack_guest_cpu_mode: host-model # Default CPU mode, nice for some OSes that kernel panic on the QEMU legacy default.

# NFS vars

nfs_location: /etc/exports
nfs_exports:
  - /export/primary
  - /export/secondary
