- name: Restart libvirt
  ansible.builtin.systemd_service:
    name: libvirtd
    state: restarted
    enabled: true

- name: Reload apparmor
  ansible.builtin.command:
    cmd: "apparmor_parser -R /etc/apparmor.d/{{ item }}"
  loop:
    - usr.sbin.libvirtd
    - usr.lib.libvirt.virt-aa-helper
  become: true

- name: Apply netplan
  ansible.builtin.command:
    cmd: netplan apply
  become: true
  async: 30
  poll: 0
