- name: Restart libvirt
  ansible.builtin.systemd_service:
    name: libvirtd
    state: restarted
    enabled: true

- name: Restart cloudstack-agent
  ansible.builtin.systemd_service:
    name: cloudstack-agent
    state: restarted

- name: Reload apparmor
  ansible.builtin.command:
    cmd: "apparmor_parser -R /etc/apparmor.d/{{ item }}"
  loop:
    - usr.sbin.libvirtd
    - usr.lib.libvirt.virt-aa-helper
  become: true

- name: Generate netplan
  ansible.builtin.command:
    cmd: netplan generate
  become: true

- name: Apply netplan
  ansible.builtin.command:
    cmd: netplan apply
  become: true

- name: Restart systemd-networkd
  ansible.builtin.systemd_service:
    name: systemd-networkd
    state: restarted

