---
- name: Install Apache management server
  ansible.builtin.apt:
     name:
       - cloudstack-management
       - mysql-server
       - cloudstack-usage
     state: present
     update_cache: yes
     cache_valid_time: 3600

- name: Prepare ARM hosts for virtualizing if ARM is in KVM cluster
  ansible.builtin.blockinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    marker: "# {mark} arm64 cpu"
    block: |
      server_id = 1
      sql-mode="STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION,ERROR_FOR_DIVISION_BY_ZERO,NO_ZERO_DATE,NO_ZERO_IN_DATE,NO_ENGINE_SUBSTITUTION"
      innodb_rollback_on_timeout=1
      innodb_lock_wait_timeout=600
      max_connections=1000
      log-bin=mysql-bin
      binlog-format = 'ROW'
  notify: Restart MySQL server

- name: Check if Cloudstack's database has already been made #Checks the database for MySQL to print 0 (the empty database ShapeBlue sends out.)
  ansible.builtin.command:
    cmd: mysql -N -B -e "SELECT COUNT(*) FROM information_schema.schemata WHERE schema_name='cloud';"
  register: cloudstack_database
  changed_when: false

- name: Initialize CloudStack database
  ansible.builtin.command:
    cmd: |
      cloudstack-setup-databases cloud:{{ cloud_db_password }}@localhost
      --deploy-as=root: -i {{ groups['cloudstack_mgmt'][0] }}
  when: cloudstack_database.stdout | int == 0
  no_log: true

- name: Check if management server is configured
  ansible.builtin.stat:
    path: /etc/cloudstack/management/log4j2.xml
  register: cloudstack_management_started

- name: Start CloudStack management server script
  ansible.builtin.command:
    cmd: cloudstack-setup-management
    creates: /etc/cloudstack/management/log4j2.xml
  when: not cloudstack_management_started.stat.exists

- name: Enable and start CloudStack management
  ansible.builtin.systemd_service:
    name: cloudstack-management
    enabled: true
    state: started
    daemon_reload: true
  become: true
